# Generated by Django 3.1 on 2020-08-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200811_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.BinaryField(max_length=500),
        ),
    ]
