# Generated by Django 3.1 on 2020-08-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200812_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='author',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
