# Generated by Django 3.1 on 2020-08-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200811_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='password',
            field=models.BinaryField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.BinaryField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reply',
            name='password',
            field=models.BinaryField(max_length=500),
        ),
    ]
